export const BOTTOM_TAB_BAR_HEIGHT = 49;
export const PATROL_DETAILS_TITLE_HEIGHT = 88;
export const PATROL_DETAILS_CONTENT_HEIGHT = 310;
export const TRACKING_STATUS_TITLE_HEIGHT = 88;
export const TRACKING_STATUS_INLINE_BUTTONS_HEIGHT = 160;
export const TRACKING_STATUS_STACKED_BUTTONS_HEIGHT = 210;
export const MAP_OVERLAY_BUTTON_SIZE = 49;
export const MAP_OVERLAY_BUTTON_BOTTOM_MARGIN = 16;
export const SUBJECT_DETAILS_CONTENT_HEIGHT = 150;

const margin = {
  small: 8,
  standard: 16,
};

export { margin };
