export const SUBJECT_GROUPS_MOCK_DATA = {
  data: [
    {
      name: 'Rhinos',
      id: 'b550f62f-4a2a-4539-af79-253457e988fd',
      subgroups: [],
      subjects: [
        {
          content_type: 'observations.subject',
          id: 'cf68833a-a1ad-4afc-9e02-d98b6006ac2b',
          name: 'Fatu',
          subject_type: 'wildlife',
          subject_subtype: 'rhino',
          common_name: null,
          additional: {
            rgb: '22, 250, 32',
            sex: 'female',
            region: '',
            country: '',
            external_id: '',
            tm_animal_id: '',
            external_name: '',
          },
          created_at: '2022-08-15T16:23:17.933641-07:00',
          updated_at: '2023-11-30T12:04:21.514122-08:00',
          is_active: true,
          user: null,
          region: '',
          country: '',
          sex: 'female',
          tracks_available: true,
          image_url: '/static/rhino-black-female.svg',
          last_position_status: {
            last_voice_call_start_at: null,
            radio_state_at: null,
            radio_state: 'na',
          },
          last_position_date: '2024-05-27T01:04:01+00:00',
          last_position: {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [
                -109.2586831172305,
                -27.10600717126486,
              ],
            },
            properties: {
              title: 'Fatu',
              subject_type: 'wildlife',
              subject_subtype: 'rhino',
              id: 'cf68833a-a1ad-4afc-9e02-d98b6006ac2b',
              stroke: '#16FA20',
              'stroke-opacity': 1.0,
              'stroke-width': 2,
              image: 'https://easterisland.pamdas.org/static/rhino-black-female.svg',
              last_voice_call_start_at: null,
              location_requested_at: null,
              radio_state_at: '1970-01-01T00:00:00+00:00',
              radio_state: 'na',
              coordinateProperties: {
                time: '2024-05-27T01:04:01+00:00',
              },
              DateTime: '2024-05-27T01:04:01+00:00',
            },
          },
          device_status_properties: [
            {
              label: 'Temp',
              units: 'C',
              value: 19.9,
            },
            {
              label: 'Voltage',
              units: 'V',
              value: 3.76,
            },
            {
              label: 'speed',
              units: 'km/h',
              value: 24.0,
            },
          ],
          url: 'https://easterisland.pamdas.org/api/v1.0/subject/cf68833a-a1ad-4afc-9e02-d98b6006ac2b',
        },
        {
          content_type: 'observations.subject',
          id: 'c685d0c8-6663-4a84-97e1-b9d7a9d3d2b2',
          name: 'Najin',
          subject_type: 'wildlife',
          subject_subtype: 'rhino',
          common_name: null,
          additional: {
            rgb: '68, 190, 242',
            sex: 'male',
            region: '',
            country: '',
            tm_animal_id: '',
          },
          created_at: '2022-08-15T16:23:16.994668-07:00',
          updated_at: '2022-11-30T05:55:18.146758-08:00',
          is_active: true,
          user: null,
          region: '',
          country: '',
          sex: 'male',
          tracks_available: true,
          image_url: '/static/rhino-black-male.svg',
          last_position_status: {
            last_voice_call_start_at: null,
            radio_state_at: null,
            radio_state: 'na',
          },
          last_position_date: '2024-05-27T01:04:01+00:00',
          last_position: {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [
                -109.3506276748008,
                -27.11396915154021,
              ],
            },
            properties: {
              title: 'Najin',
              subject_type: 'wildlife',
              subject_subtype: 'rhino',
              id: 'c685d0c8-6663-4a84-97e1-b9d7a9d3d2b2',
              stroke: '#44BEF2',
              'stroke-opacity': 1.0,
              'stroke-width': 2,
              image: 'https://easterisland.pamdas.org/static/rhino-black-male.svg',
              last_voice_call_start_at: null,
              location_requested_at: null,
              radio_state_at: '1970-01-01T00:00:00+00:00',
              radio_state: 'na',
              coordinateProperties: {
                time: '2024-05-27T01:04:01+00:00',
              },
              DateTime: '2024-05-27T01:04:01+00:00',
            },
          },
          device_status_properties: [
            {
              label: 'Temp',
              units: 'C',
              value: 20.76,
            },
            {
              label: 'Voltage',
              units: 'V',
              value: 3.73,
            },
            {
              label: 'speed',
              units: 'km/h',
              value: 2.01,
            },
          ],
          url: 'https://easterisland.pamdas.org/api/v1.0/subject/c685d0c8-6663-4a84-97e1-b9d7a9d3d2b2',
        },
      ],
    },
  ],
  status: {
    code: 200,
    message: 'OK',
  },
};
